--
-- PostgreSQL database dump
--

\restrict Yntm4cCov8rN2rB2qn8fgDsn0b10RDq56T4crZfDGMevJxyZzhMOjZjGBdGkoNB

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: match_results; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.match_results (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    fit_score integer NOT NULL,
    gap_analysis text,
    job_id bigint,
    matched_skills jsonb,
    missing_skills jsonb,
    resume_id bigint
);


ALTER TABLE public.match_results OWNER TO postgres;

--
-- Name: match_results_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.match_results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.match_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: match_results; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.match_results (id, created_at, fit_score, gap_analysis, job_id, matched_skills, missing_skills, resume_id) FROM stdin;
1	2026-08-09 09:19:02.020459	95	The candidate is an excellent fit for this position, meeting all requested requirements with strong hands-on experience in Java, Spring Boot, and distributed microservices. In addition to core skills, they offer valuable experience with cloud deployment, Docker, and Apache Kafka. The primary consideration is that the candidate is an expected 2027 graduate, so work schedule or contract type should be clarified.	1	["Java", "Spring Boot", "Microservices"]	[]	1
\.


--
-- Name: match_results_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.match_results_id_seq', 1, true);


--
-- Name: match_results match_results_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.match_results
    ADD CONSTRAINT match_results_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict Yntm4cCov8rN2rB2qn8fgDsn0b10RDq56T4crZfDGMevJxyZzhMOjZjGBdGkoNB

