apiVersion: v1
kind: Service
metadata:
  name: matching-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: matching-service
  ports:
    - port: {{ .Values.matchingService.port }}
      targetPort: {{ .Values.matchingService.port }}
  type: NodePort