apiVersion: v1
kind: ConfigMap
metadata:
  name: matching-service-config
  namespace: {{ .Values.namespace }}
data:
  UPLOAD_SERVICE_URL: "http://upload-service:{{ .Values.uploadService.port }}"
  GEMINI_API_URL: {{ .Values.matchingService.geminiApiUrl | quote }}