apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: upload-service
  ports:
    - port: {{ .Values.uploadService.port }}
      targetPort: {{ .Values.uploadService.port }}
  type: ClusterIP